# Dev Environment
name: cirrhosis_death
channels:
  - defaults
  # - pytorch
  # - fastai
  - conda-forge
  - plotly
  - bioconda
dependencies:
  - python
  - numpy<1.23
  - pandas
  - pandas-profiling
  - sweetviz
  - scipy
  # plotting
  - matplotlib
  - plotly
  - seaborn
  - umap-learn
  # - graphviz
  - python-graphviz
  # ML, stats
  - scikit-learn
  - pingouin
  # other
  - tqdm # progress bars
  - xmltodict # configs
  - openpyxl # xml
  - omegaconf
  - hydra-core
  # snakemake
  - snakemake-minimal>=6.0.0
  # jupyter
  - ipykernel
  - ipython
  - ipywidgets
  - jupytext
  - jupyterlab # standalone jupyter installation
  - jupyterlab_code_formatter
  - jupyterlab-git
  # - jupyter_contrib_nbextensions
  - jupyter-dash
  - papermill # execute ipynb's
  # survival analysis
  - lifelines
  - statsmodels
  # dev
  - pytest
  - pytest-cov
  - jupytext
  - yapf # code formatting7  
  - pip
  - pip:
    - -e .
    - mrmr_selection
    - njab