# Environment with additional packages pinned
name: cirrhosis_death
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<1.23
  - pandas<2 # some pandas function will need to be updated
  - ydata-profiling
  - sweetviz=2.2
  - scipy
  # plotting
  - matplotlib<3.7
  - plotly
  - seaborn
  - umap-learn=0.5
  # - graphviz
  - python-graphviz
  # ML, stats
  - scikit-learn=1.3
  - pingouin=0.5
  # other
  - tqdm # progress bars
  - xmltodict # configs
  - openpyxl # xml
  - omegaconf
  - hydra-core
  # snakemake
  - snakemake-minimal>=6.0.0
  # jupyter
  - ipykernel
  - ipython
  - ipywidgets
  - jupytext
  - jupyterlab # standalone jupyter installation
  - jupyterlab_code_formatter
  - jupyterlab-git
  # - jupyter_contrib_nbextensions
  - jupyter-dash
  - papermill # execute ipynb's
  # survival analysis
  - lifelines=0.27
  - statsmodels=0.13
  # dev
  - pytest
  - pytest-cov
  - jupytext
  - yapf # code formatting
  - pip
  - pip:
      - mrmr_selection==0.2.8
      - njab==0.0.3
      - heatmapz==0.0.4
      - pretty-jupyter
