# environment build on 2023-11-09 on windows - list all dependencies
name: cirrhosis_death
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - amply=0.1.6
  - ansi2html=1.8.0
  - ansiwrap=0.8.4
  - antlr-python-runtime=4.9.3
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astor=0.8.1
  - asttokens=2.0.5
  - attrs=23.1.0
  - autograd=1.5
  - autograd-gamma=0.5.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - black=23.3.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.2
  - configargparse=1.4
  - connection_pool=0.0.3
  - contourpy=1.0.5
  - coverage=7.2.2
  - cryptography=41.0.3
  - cycler=0.11.0
  - dash=2.7.0
  - datrie=0.8.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.18.1
  - dpath=2.1.6
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - flask=2.2.2
  - flask-compress=1.13
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - formulaic=0.6.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - future=0.18.3
  - getopt-win32=0.1
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.37
  - glib=2.69.1
  - glpk=4.65
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gts=0.7.6
  - harfbuzz=4.3.0
  - htmlmin=0.1.12
  - humanfriendly=10.0
  - hydra-core=1.3.2
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.4
  - imagehash=4.3.1
  - importlib-metadata=6.0.0
  - importlib-resources=6.1.0
  - importlib_resources=6.1.0
  - iniconfig=1.1.1
  - intel-openmp=2023.1.0
  - interface_meta=1.3.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - itsdangerous=2.0.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-dash=0.4.2
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=7.4.9
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab-git=0.44.0
  - jupyterlab_code_formatter=2.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - jupytext=1.15.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgd=2.3.3
  - libiconv=1.16
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - lifelines=0.27.8
  - littleutils=0.2.2
  - llvmlite=0.41.0
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - multimethod=1.9.1
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclassic=0.5.5
  - nbclient=0.8.0
  - nbdime=3.2.1
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - numba=0.58.0
  - numexpr=2.8.7
  - numpy=1.22.3
  - numpy-base=1.22.3
  - omegaconf=2.3.0
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=3.0.12
  - outdated=0.2.2
  - packaging=23.1
  - pandas=1.5.3
  - pandas-flavor=0.6.0
  - pandocfilters=1.5.0
  - pango=1.50.7
  - papermill=2.4.0
  - parso=0.8.3
  - pathspec=0.10.3
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - phik=0.12.3
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pingouin=0.5.3
  - pip=23.3
  - pixman=0.40.0
  - plac=1.3.4
  - platformdirs=3.10.0
  - plotly=5.9.0
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=1.10.12
  - pygments=2.15.1
  - pynndescent=0.5.10
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyreadline3=3.4.1
  - pysocks=1.7.1
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - referencing=0.30.2
  - requests=2.28.1
  - reretry=0.11.8
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-learn=1.3.0
  - scipy=1.9.3
  - seaborn=0.12.2
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=4.0.0
  - snakemake-minimal=7.32.4
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - stopit=1.1.2
  - sweetviz=2.2.1
  - tabulate=0.8.10
  - tangled-up-in-unicode=0.2.0
  - tbb=2021.8.0
  - tenacity=8.2.2
  - terminado=0.17.1
  - textwrap3=0.9.2
  - threadpoolctl=2.2.0
  - throttler=1.2.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toposort=1.10
  - tornado=6.3.3
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typeguard=2.13.3
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - umap-learn=0.5.4
  - urllib3=1.26.18
  - vc=14.2
  - visions=0.7.5
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.14.1
  - xarray=2023.6.0
  - xmltodict=0.13.0
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - yapf=0.31.0
  - ydata-profiling=4.1.1
  - ypy-websocket=0.8.2
  - yte=1.5.1
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - category-encoders==2.6.3
      - cerberus==1.3.5
      - heatmapz==0.0.4
      - lxml==4.9.3
      - mistune==0.8.4
      - mrmr-selection==0.2.8
      - nbconvert==6.5.4
      - njab==0.0.3
      - polars==0.19.12
      - pretty-jupyter==2.0.5
