# missing in CircaFlow in comparison to ProDoc
# - 'IgM', 'IgG', 'IgA'
# - 'Icterus', 'SBP', 'Cancer', 'Depression', 'Psychiatric'

rename_dict = {
    'SampleID': 'SampleID',
    'Label: ': 'ID',
    'Comment on sample: ': 'CommentOnSample',
    'DateInflSample': 'DateInflSample',
    'Age': 'Age',
    'Healthy': 'Healthy',
    'cirrose ætiologi. Alkohol = 1, 2 = HCV, 3 = cryptogen, 4= NASH, 5= anit1-trypsin mangel, 6 hæmokromatose, 7=autoimmun og PBC, 8=HBV, 9 kutan porfyri': 'cirrose ætiologi. Alkohol = 1, 2 = HCV, 3 = cryptogen, 4= NASH, 5= anit1-trypsin mangel, 6 hæmokromatose, 7=autoimmun og PBC, 8=HBV, 9 kutan porfyri',
    'EtiAlco': 'EtiAlco',
    'EtiFat': 'EtiFat',
    'EtiHBV': 'EtiHBV',
    'EtiHCV': 'EtiHCV',
    'EtiPBC': 'EtiPBC',
    'EtiAIH': 'EtiAIH',
    'EtiMTX': 'EtiMTX',
    'EtiOther': 'EtiOther',
    'EtiUnknown': 'EtiUnknown',
    'CirrhosisYear': 'CirrhosisYear',
    'Height(cm)': 'Height(cm)',
    'Weight(kg)': 'Weight(kg)',
    'BMI': 'BMI',
    'Sex': 'Sex',
    'Ascites': 'Ascites',
    'Decompensation': 'DecompensationAtIncl',  # DecompensationAtInclusion
    'EsoBleeding': 'EsoBleeding',
    'HE': 'HE',
    'HRS': 'HRS',
    'Alcohol (0=no overuse, 1=former overuse, 2= ongoing overuse, 3=episodically)': 'Alcohol (0=no overuse, 1=former overuse, 2= ongoing overuse, 3=episodically)',
    'Items pr. week (ongoing)': 'Items pr. week (ongoing)',
    'Hypertension': 'Hypertension',
    'Diabetes': 'Diabetes',
    'InsulinDependent': 'InsulinDependent',
    'HeartDisease': 'HeartDisease',
    'Hyperkolesterolæmi kolesterol >5 (0=nej, 1=ja 2 = simvastatin)': 'Hyperkolesterolæmi kolesterol >5 (0=nej, 1=ja 2 = simvastatin)',
    'HighCholesterol': 'HighCholesterol',
    'HVPG': 'HVPG',
    'NonselectBetaBlock': 'NonselectBetaBlock',
    'Statins': 'Statins',
    'ChildPughClass (1=a, 2=b, 3=c) ': 'ChildPughClass (1=a, 2=b, 3=c) ',
    'ChildPugh': 'ChildPugh',
    'Leucocytes': 'Leucocytes',
    'kreatinin mg/dl': 'kreatinin mg/dl',
    'GradeHE': 'GradeHE',
    'MELD-Na': 'MELD-Na',
    'MELD': 'MELD-score',
    'Hgb': 'Hgb',
    'neutrocyt': 'neutrocyt',
    'monocyt': 'monocyt',
    'lymfocyt': 'lymfocyt',
    'trombocyt': 'Platelets',
    'albumin': 'Albumin',
    'Sodium': 'Sodium',
    'Potassium': 'Potassium',
    'Creatinine': 'Creatinine',
    'GFR': 'GFR',
    'Karbamid': 'Karbamid',
    'ALAT': 'ALAT',
    'ASAT': 'ASAT',
    'Bilirubin': 'Bilirubin',
    'bas.fos': 'bas.fos',
    'CRP': 'CRP',
    'INR': 'INR',
    'PP': 'pp',
    'Chol': 'Chol',
    'HDL': 'HDL',
    'LDL': 'LDL',
    'VLDL': 'VLDL',
    'Trigl': 'Trigl',
    'gamma GT': 'gamma GT',
    'LDH': 'LDH',
    'Cystatin C': 'Cystatin C',
    'Projekt ID': 'Projekt ID',
    'DateInflSample.1': 'DateInflSample',
    'CommentAdmission': 'CommentAdmission',
    '90days': '90days',
    '180days': '180days',
    'AdmittetBlood': 'AdmittetBlood',
    'DateFirstAdmission': 'DateFirstAdmission',  # 'DateAdm',
    'Cause': 'Cause',
    'TimeToAdm': 'TimeToAdm',
    'Adm180': 'Adm180',
    'Adm90': 'Adm90',
    'LiverAdm90': 'LiverAdm90',
    'LiverAdm180': 'LiverAdm180',
    'DateDeath': 'DateDeath',
    'TimeToDeath': 'TimeToDeath',
    'CauseOfDeath': 'CauseOfDeath',
    'AdmittetBlood.1': 'AdmittetBlood.1',
    'is "Yes" if admitted during inflammation sample': 'is "Yes" if admitted during inflammation sample',
    'Leuko': 'Leuko'
}
