Study ID: ''
DateDiagnose: ''
DateInflSample: ''
TimeToInflSample: ''
Age: ''
Sex: ''
MaritalStatus: ''
EtiAlco: ''
EtiFat: ''
EtiHBV: ''
EtiHCV: ''
EtiPBC: ''
EtiAIH: ''
EtiMTX: ''
EtiOther: ''
EtiUnknown: ''
DecomensatedAtDiagnosis: ''
Ascites: ''
EsoBleeding: ''
HRS: ''
HE: ''
Icterus: ''
SBP: ''
IgM: ''
IgG: ''
IgA: ''
Hgb: ''
Leucocytes: ''
Platelets: ''
Bilirubin: ''
Albumin: ''
CRP: ''
pp: ''
INR: ''
ALAT: ''
Sodium: ''
Creatinine: ''
Potassium: ''
HbA1c: ''
Heartdisease: ''
Hypertension: ''
HighCholesterol: ''
Cancer: ''
Depression: ''
Psychiatric: ''
Diabetes: ''
IschemicHeart: ''
HeartFailure: ''
Arrythmia: ''
OtherHeart: ''
TypeDiabetes: ''
InsulinDependent: ''
OtherComorb: ''
Statins: ''
NonselectBetaBlock: ''
DateDeath: ''
TimeToDeath: ''
TimeToDeathFromSample: ''
TimeToDeathFromInclu: ''
CauseOfDeath: ''
TimeToAdmFromDiagnose: ''
TimeToAdmFromSample: ''
Admissions: ''
DateFirstAdmission: ''
'DateImmunoglobulins ': ''
'DateBiochemistry ': ''
MELD-score: ''
MELD-Na: ''
DateInclusion: ''
DiagnosisPlace: ''
ChildPugh: ''
HeartDiseaseTotal: ''
NoAdmTotal: ''
Adm6mInfl: ''
AdmUNeg6m: ''
AdmFDiagn6m: ''
TimeToAdmFromInclu: ''
LiverRelated1admFromInclu: ''
AmountLiverRelatedAdm: ''
AdmTotalFInclu180: ''
