SampleID: ""
CBMRID: ""
newid: ""
cohort: ""
Sample_type: ""
sampletype: ""
timepoint: ""
IL8: ""
VEGFA: ""
CD8A: ""
MCP3: ""
GDNF: ""
CDCP1: ""
CD244: ""
IL7: ""
OPG: ""
LAP_TGFb1: ""
uPA: ""
IL6: ""
IL17C: ""
MCP1: ""
IL17A: ""
CXCL11: ""
AXIN1: ""
TRAIL: ""
IL20RA: ""
CXCL9: ""
CST5: ""
IL2RB: ""
IL1_a: ""
OSM: ""
IL2: ""
CXCL1: ""
TSLP: ""
CCL4: ""
CD6: ""
SCF: ""
IL18: ""
SLAMF1: ""
TGFa: ""
MCP4: ""
CCL11: ""
TNFSF14: ""
FGF23: ""
IL10RA: ""
FGF5: ""
MMP1: ""
LIFR: ""
FGF21: ""
CCL19: ""
IL15RA: ""
IL10RB: ""
IL22_RA1: ""
IL18R1: ""
PDL1: ""
BetaNGF: ""
CXCL5: ""
TRANCE: ""
HGF: ""
IL12B: ""
IL24: ""
IL13: ""
ARTN: ""
MMP10: ""
IL10: ""
TNF: ""
CCL23: ""
CD5: ""
CCL3: ""
Flt3L: ""
CXCL6: ""
CXCL10: ""
4EBP1: ""
IL20: ""
SIRT2: ""
CCL28: ""
DNER: ""
ENRAGE: ""
CD40: ""
IL33: ""
IFNg: ""
FGF19: ""
IL4: ""
LIF: ""
NRTN: ""
MCP2: ""
CASP8: ""
CCL25: ""
CX3CL1: ""
TNFRSF9: ""
NT3: ""
TWEAK: ""
CCL20: ""
ST1A1: ""
STAMBP: ""
IL5: ""
ADA: ""
TNFB: ""
CSF1: ""
