from config import folder_reports
from config import fname_pkl_clinic
from config import fname_pkl_olink
from config import TARGETS

print(folder_reports)

rule all:
    input: 
        t= expand(
            ["{out_path}/{target}/1_explorative_analysis.ipynb",
             "{out_path}/{target}/2_tree.ipynb"],
            out_path=folder_reports,
            target=TARGETS)

nb='0_load_raw_data.ipynb'
rule prepare_data:
    input:
        nb=nb
    output:
        clinic_pkl=fname_pkl_clinic, 
        olink_pkl=fname_pkl_olink,
        profiling_report_clinic=f"{folder_reports}/clinic_data_profil.html",
        profiling_report_olink=f"{folder_reports}/olink_data_profil.html",
        nb=f"{folder_reports}/{nb}",
    shell:
        "papermill {input.nb} {output.nb}"
        " --inject-paths"
        " && jupyter nbconvert {output.nb} --to html"
        " && pandas_profiling {output.clinic_pkl}  {output.profiling_report_clinic} -m"
        " && pandas_profiling {output.olink_pkl}  {output.profiling_report_olink} -m"


nb='1_explorative_analysis.ipynb'
rule analysis:
    input:
        fname_pkl_olink,
        fname_pkl_clinic,
        nb=nb
    output:
        nb="{out_path}/{target}"f"/{nb}"
    shell:
        "papermill {input.nb} {output.nb}"
        " --inject-paths"
        " -r TARGET {wildcards.target}"
        " && jupyter nbconvert {output.nb} --to html"


nb='2_tree.ipynb'
rule decision_tree:
    input:
        fname_pkl_olink,
        fname_pkl_clinic,
        nb=nb
    output:
        nb="{out_path}/{target}"f"/{nb}"
    shell:
        "papermill {input.nb} {output.nb}"
        " --inject-paths"
        " -r TARGET {wildcards.target}"
        " && jupyter nbconvert {output.nb} --to html"
